<?php

/**
 * @file
 * Provides a student entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\asenext_test\Entity\Student;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function asenext_test_theme() {
  return [
    'student' => [
      'render element' => 'elements',
    ],
    'result' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for student templates.
 *
 * Default template: student.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the student information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_student(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function asenext_test_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish students.
      $storage = \Drupal::entityTypeManager()->getStorage('student');
      $student_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($student_ids) as $student) {
        $student->set('status', FALSE);
        $student->save();
      }

      // Unpublish results.
      $storage = \Drupal::entityTypeManager()->getStorage('result');
      $result_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($result_ids) as $result) {
        $result->set('status', FALSE);
        $result->save();
      }

      break;

    case 'user_cancel_reassign':
      // Anonymize students.
      $storage = \Drupal::entityTypeManager()->getStorage('student');
      $student_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($student_ids) as $student) {
        $student->setOwnerId(0);
        $student->save();
      }

      // Anonymize results.
      $storage = \Drupal::entityTypeManager()->getStorage('result');
      $result_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($result_ids) as $result) {
        $result->setOwnerId(0);
        $result->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function asenext_test_user_predelete(UserInterface $account) {
  // Delete students.
  $storage = \Drupal::entityTypeManager()->getStorage('student');
  $student_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $students = $storage->loadMultiple($student_ids);
  $storage->delete($students);

  // Delete results.
  $storage = \Drupal::entityTypeManager()->getStorage('result');
  $result_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $results = $storage->loadMultiple($result_ids);
  $storage->delete($results);
}

/**
 * Prepares variables for result templates.
 *
 * Default template: result.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the result information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_result(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
